#!/bin/sh

OPS=$(cat /sys/kernel/sched_ext/root/ops 2>/dev/null || echo "")

if [ -n "$OPS" ]; then
    echo "[INFO] Stopping $OPS ..."
    sudo rm /sys/fs/bpf/sched_ext/sched_ops
    echo "[INFO] Done."
else 
    echo "[INFO] No sched_ext running."
fi
